apiVersion: v1
kind: Service
metadata:
  name: my-n8n-service
spec:
  type: NodePort
  selector:
    app: my-n8n
  ports:
    - port: 80
      targetPort: 5678  # Should match containerPort in deployment
      nodePort: 30080   # You can open app at http://localhost:30080

